### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by MattCollins84**
Use Nano Events by extending ES6 classes

### CODE REVIEW

**Comment by ai** [comment]
Thanks for the idea of this section. Big contribution :).

But this way of including NanoEvents have few problems:

1. `on()` method will not have useful JSDoc with a list of the available method. [example](https://github.com/logux/logux-core/blob/master/log.js#L49-L72).
2. Some projects may already be extended from other class. So this method is not universal.
3. Not all classes need to put `emit()` to public space.

What do you think about this way:

```js
class Foo {
  constructor () {
    this.events = new NanoEvents()
  }
  on () {
    return this.events.on.apply(this.events, arguments)
  }
  someInternalLogic() {
    if (someMagic()) {
      this.event.emit()
    }
  }
}
```

I completely agree that we need this section in the docs. The question only the way which will be recommended.

**Comment by MattCollins84** [comment]
I think that the use of the `extend` syntax is good because it explicitly shows the developer that we are creating a new class `Foo`, but also implementing functionality of another class `NanoEvents` - and the developer can then refer directly to the documentation for `NanoEvents` to see what is available.

I agree that sometimes a developer might not want `emit()` to be exposed publicly, however I would just say that in this case the developer would not use `extend` :) Your example is also a good solution to wrap the functionality but I do not think it is explicit. Also, `emit()` is still public here via `this.events.emit()` :)

I do not think we have to choose between my solution or your solution - I think we could have both as examples and let the developer select which he thinks is best!

**Comment by ai** [comment]
Main problem — how you will available events by JSDoc? Right now JSDoc will inherit from NanoEvents without explicit names.

I understand that choice is always better. But all my experience in PostCSS shows that it is much better to show only one way in docs. If somebody needs another way (like if somebody prefers `extend`) it still could use it.

So we need to choose the universal way. Right now we have two problems:

* Harder to make docs.
* `emit` JSDoc will be mixed with user’s class JSDoc (so `emit` method will be public).
* You can accidentally override `emit` method in your class.

I agree that both methods is good. You can still use your method in the code. But I must choice the only one method :(.

**Comment by StreetStrider** [comment]
Generally speaking, composition is better than inheritance. From my perspective, much of the inheritance use-cases can be rewritten in a composition manner without having any harms later. (Even reduce some possible issues, related to additional Liskov hassle or interface clash.)

> Your example is also a good solution to wrap the functionality but I do not think it is explicit

Why not? Both variants are totally explicit. By instantiating `events` inside some `foo` we manifest that «it supports pubsub», `events` is an explicit part of interface now, just like `extends NanoEvents` means the same.

> Also, emit() is still public here via this.events.emit().

Indeed it is, but at least it is on the different interface (NanoEvents). This is better from SoC perspective and in a total agreement with the Law of Demeter.

**Pull request closed without merging**
