### PR TITLE
Add unbindAll() method

### PR DESCRIPTION
**Pull request by rodweb**
It may be useful to completely reset NanoEvents instance, clearing all event listeners.
For example, during testing:

```js
import emitter from '../src/Emitter'; // has NanoEvents instance;

beforeEach(() => emitter.unbindAll());

it ('test1', () => { /* using clean instance of NanoEvents */ })
it ('test2', () => { /* using clean instance of NanoEvents */ })
```

### CODE REVIEW

**Comment by ai** [comment]
10% extra size is very big price for one method for test purposes.

First, there is no need to use `hasOwnProperty`. Also deleting properties is slow, just do `this.events = { }`.

**Comment by rodweb** [comment]
Replacing contents of `unbindAll()` with `this.events = { }` results in ~3% size increase instead of 10%. This particular use case is the one I encountered while writing tests. I believe there can be more, but can't come up with any right now.

**Comment by rodweb** [comment]
Just like you said, I'm thinking that having a certain method to clean all listeners is better for understanding, while `this.events` seems to be more internal, and replacing it with new `Object` instance requires looking into the sources first to make sure no bindings are broken, etc.

One can still add a small wrapper around `NanoEvents` implementing `unbindAll()` without bloating the original package, though 🙂 

```js
class Emitter extends NanoEvents {
  unbindAll() {
    this.events = { }
  }
}
```

**Comment by ai** [comment]
I agree that it is internal method.

If we need it only for tests I know other solution. We can move this code to separated file `helpers.js`. Also we can put `clone()` there (or something similar).

**Comment by rodweb** [comment]
Can you demonstrate the way these helpers will be used? Does `NanoEvents` gets imported into `helpers.js` and extended with new methods?

**Comment by ai** [comment]
@rodweb you will load this file only if you need it (only in tests):

```js
import { unbindAll } from `nanoevents/helpers`
```

**Comment by ai** [comment]
Great! Last thing default `emitter.events` is `{ }`, not `[]`

**Comment by rodweb** [comment]
> Great! Last thing default `emitter.events` is `{ }`, not `[]`

I don't see where it is.

**Comment by ai** [comment]
Released in 0.4

**Pull request merged**
