### PR TITLE
fix(types): export createNanoEvents as namespace

### LINKED ISSUE #40: Using this in a TypeScript library with `"declaration": true` fails
## Description

The error is shown below.

```
Public property 'events' of exported class has or is using name 'Emitter' from external module "/path/to/node_modules/nanoevents/index" but cannot be named
```

The fix would be to update the index.d.ts file for the project to look like this.  This works because when setting `export = createNanoEvents` then we also have to wrap everything in a namespace so that it can be accessed by external code.

```ts
declare namespace createNanoEvents {
  interface EventsMap {
    [event: string]: any
  }

  interface DefaultEvents extends EventsMap {
    [event: string]: (...args: any) => void
  }

  class Emitter<Events extends EventsMap> {
    /**
     * Event names in keys and arrays with listeners in values.
     *
     * ```js
     * emitter1.events = emitter2.events
     * emitter2.events = { }
     * ```
     */
    events: Partial<{ [E in keyof Events]: Events[E][] }>

    /**
     * Add a listener for a given event.
     *
     * ```js
     * const unbind = ee.on('tick', (tickType, tickDuration) => {
     *   count += 1
     * })
     *
     * disable () {
     *   unbind()
     * }
     * ```
     *
     * @param event The event name.
     * @param cb The listener function.
     * @returns Unbind listener from event.
     */
    on <K extends keyof Events>(this: this, event: K, cb: Events[K]): () => void

    /**
     * Calls each of the listeners registered for a given event.
     *
     * ```js
     * ee.emit('tick', tickType, tickDuration)
     * ```
     *
     * @param event The event name.
     * @param args The arguments for listeners.
     */
    emit <K extends keyof Events>(
      this: this,
      event: K,
      ...args: Parameters<Events[K]>
    ): void
  }
}

/**
 * Create event emitter.
 *
 * ```js
 * import createNanoEvents from 'nanoevents'
 *
 * class Ticker {
 *   constructor() {
 *     this.emitter = createNanoEvents()
 *   }
 *   on(...args) {
 *     return this.emitter.on(...args)
 *   }
 *   tick() {
 *     this.emitter.emit('tick')
 *   }
 * }
 * ```
 */
declare function createNanoEvents<Events extends createNanoEvents.EventsMap = createNanoEvents.DefaultEvents> (
): createNanoEvents.Emitter<Events>

export = createNanoEvents
```

### PR DESCRIPTION
**Pull request by ifiokjr**
Closes #40

### CODE REVIEW

**Comment by TrySound** [comment]
Why namespaces even necessary here? They are kinda legacy already. I'm sure TS is able to have definitions like regular modules.

**Comment by TrySound** [comment]
Maybe implement types like I did in flow with normal exports? I also used tuples instead of functions in generics.
https://github.com/flow-typed/flow-typed/pull/3759/files

**Comment by ifiokjr** [comment]
Because the types are using `export = createNanoEvents` the only way to also export other types is to wrap them in a namespace.

**Comment by ai** [comment]
Yeap, let’s merge it if we have a problem and have no other solution.

I will release it later with a new ESM approach (bad ESM implementation in webpack force everyone to use named exports).

**Comment by TrySound** [comment]
@ai If you go with `exports.default` approach. This change can be reverted and `export default` can be used instead of `export = `

**Comment by ai** [comment]
@TrySound I think I will move to named export in next few days

**Pull request merged**
