### PR TITLE
Size reduction by 14 B

### PR DESCRIPTION
**Pull request by gwer**
Remove bitshifting hack.
Remove variables reuse.
Use `[].slice` for `Object.prototype` properties collision fix.

### CODE REVIEW

**Comment by gwer** [comment]
Are you sure `./test/benchmark` should exist?

**Comment by ai** [comment]
Oops, it is a wrong `nano*` project :D

I thought I was in Nano ID

**Comment by ai** [comment]
Thanks. Released in 1.0.8.

**Comment by StreetStrider** [comment]
That was a beautiful in-place hack.

**Pull request merged**
